### ISSUE TITLE
Plugin causing MIME error

### ISSUE THREAD

**Issue by cusxio** [applicazza/fastify-nextjs#1]
It seems that there's some problem with this plugin.

Reproduction:
https://github.com/cusxio/fastify-nextjs-test

The JS files seems to be sent with the incorrect mime type? So they don't load, and NextJs fails to initialised.

![Screenshot 2021-08-05 at 9 29 18 PM](https://user-images.githubusercontent.com/6487613/128358120-31a949cc-ddcd-43c2-935c-96c7085142ef.png)

**Comment by applicazza** [comment]
Hey, I’ve cloned your repo but could not reproduce the issue. Application started and page with word Index opened without any error (except missing favicon).

I have noticed that in your repo you start fastify on port 3001 but on screenshot it says 3000. 

Could you elaborate more on the issue?

Thanks!

**Comment by cusxio** [comment]
Good catch! My mistake. This is an incorrect report.

There was some error in my code because I had to patch this package due to https://github.com/applicazza/fastify-nextjs/blob/3940dd1c6b63c018642b52e94c1e4a5c8f90db8e/src/index.ts#L53, I needed to pass `dir` into `Next`.

With that said, I think it would help if the plugin accepts all the options passable to `Next`.

**Comment by applicazza** [comment]
@cusxio Added `dir` option to plugin configuration. It would be nice if you update your dependency to the latest one and test if it works for you.

You can grab it [here](https://www.npmjs.com/package/@applicazza/fastify-nextjs/v/0.2.0).

**Comment by cusxio** [comment]
@applicazza, it's working for me. Thank you so much for the quick turn around! 🙏🏻
